// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrg3P3HCVFlsDv7AFz4OcGBgqTcYqSFs0',
    appId: '1:786770936350:web:648c4cb1452bc8a482640f',
    messagingSenderId: '786770936350',
    projectId: 'flashstudy-3a400',
    authDomain: 'flashstudy-3a400.firebaseapp.com',
    storageBucket: 'flashstudy-3a400.appspot.com',
    measurementId: 'G-ZNGWTH9DPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArBt9yIpMwt1ZfBgOO3p43ytKtH8ehpgM',
    appId: '1:786770936350:android:c8304723cc56d2e982640f',
    messagingSenderId: '786770936350',
    projectId: 'flashstudy-3a400',
    storageBucket: 'flashstudy-3a400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGECrYnYpXSr_atFmAbYwwvXInnsayhM',
    appId: '1:786770936350:ios:e0a0ac13db66a2fe82640f',
    messagingSenderId: '786770936350',
    projectId: 'flashstudy-3a400',
    storageBucket: 'flashstudy-3a400.appspot.com',
    iosClientId: '786770936350-hpmmqifhohrotfp1qbb4aa88orkjsi1m.apps.googleusercontent.com',
    iosBundleId: 'dev.thomasqtruong.flashStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGECrYnYpXSr_atFmAbYwwvXInnsayhM',
    appId: '1:786770936350:ios:8b8acea30bc6d73a82640f',
    messagingSenderId: '786770936350',
    projectId: 'flashstudy-3a400',
    storageBucket: 'flashstudy-3a400.appspot.com',
    iosClientId: '786770936350-ki98bj70tkcsjhub63dfg4s1niia4iu1.apps.googleusercontent.com',
    iosBundleId: 'dev.thomasqtruong.flashStudy.RunnerTests',
  );
}
